import Head from "next/head";
import { Inter, Island_Moments } from "next/font/google";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });
import { useEffect, useState } from "react";
import {
  Container,
  Stack,
  Input,
  Button,
  SimpleGrid,
  Flex,
  Box,
  Modal,
  ModalOverlay,
  ModalHeader,
  ModalBody,
  ModalContent,
  ModalCloseButton,
  useDisclosure,
} from "@chakra-ui/react";
import React from "react";
import { PokemonCard, PokemonData } from "@/components";
import { Pokemon } from "@/models";
import { Header } from "@/ui/header";

export default function Home() {
  const pokemonDataModal = useDisclosure();

  const [isLoading, setIsLoading] = React.useState(false);
  const [pokemons, setPokemons] = React.useState<Pokemon[]>([]);
  const [selectedPokemon, setSelectedPokemon] = React.useState<Pokemon>();
  const [pokeOffset, setPokeOffset] = React.useState(0);

  React.useEffect(() => {
    async function getPokemon() {
      try {
        const res = await axios.get(
          `https://pokeapi.co/api/v2/pokemon/?limit=20&offset=${pokeOffset}`
        );
        if (res.data?.results!.length === 0) {
          console.error("No hay datos");
        } else {
          const promises = res.data?.results.map((result) => axios(result.url));
          const fetchedPokemon = (await Promise.all(promises)).map(
            (res) => res.data
          );

          setPokemons((prev) => [...prev, ...fetchedPokemon]);
          setIsLoading(false);
        }
      } catch (error) {
        console.error(error);
      }
    }
    getPokemon();
  }, [pokeOffset]);

  const handleNextPage = () => {
    setPokeOffset((prev) => prev + 20);
    setIsLoading(!isLoading);
  };

  const handleViewPokemon = (pokemon) => {
    setSelectedPokemon(pokemon);
    pokemonDataModal.onOpen();
  };

  return (
    <>
      <Head>
        <title>Pokemon Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        alignItems="center"
        minH="100vh"
        justifyContent="center"
        marginRight={{ md: "300px" }}
      >
        <Container>
          <Stack
            p="0"
            alignItems="center"
            spacing="0"
            justifyContent={"center"}
            alignContent={"center"}
            textAlign={"center"}
            marginTop={"50px"}
          >
            <SimpleGrid
              spacingX={{ md: "440px" }}
              spacingY="20px"
              columns={{ base: 1, sm: 1, md: 3 }}
              justifyContent={"space-between"}
            >
              {pokemons.map((pokemon: Pokemon, index: number) => (
                <Box
                  as="button"
                  key={index}
                  onClick={() => handleViewPokemon(pokemon)}
                >
                  <PokemonCard {...pokemon} />
                </Box>
              ))}
            </SimpleGrid>

            <Button
              width={"100%"}
              isLoading={isLoading}
              onClick={handleNextPage}
              display={"flex"}
              marginTop={"120px"}
              marginBottom={10}
              marginLeft={{ md: "300px" }}
              color={"#E2E2E2"}
              colorScheme={"#E2E2E2"}
              backgroundColor={"#FF0000"}
              _hover={{ bg: "#C30010", borderColor: "black" }}
              borderRadius={"xl"}
            >
              Cargas más
            </Button>
          </Stack>
        </Container>
      </Flex>
      <Modal {...pokemonDataModal} isCentered size={"xl"}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader textTransform="capitalize">
            {selectedPokemon && selectedPokemon.name}
          </ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            {selectedPokemon && <PokemonData {...selectedPokemon} />}
          </ModalBody>
        </ModalContent>
      </Modal>
    </>
  );
}
